import { existsSync, readFileSync } from 'node:fs';
import type { EnvPaths } from './envPaths';
import { parseMcpServers, type McpServer } from './mcpServers';
import type { ScriptExtension } from './weaveScripts';

/**
 * Reads and validates the declared Host MCP servers for an environment. Returns an
 * empty list when `mcp-servers.yaml` does not exist (nothing declared yet).
 */
export function loadDeclaredMcpServers(paths: EnvPaths): McpServer[] {
  const content = existsSync(paths.mcpServersYaml)
    ? readFileSync(paths.mcpServersYaml, 'utf8')
    : '';
  return parseMcpServers(content, { envRoot: paths.root });
}

/**
 * Generates the post-isolation step that registers every declared Host MCP server
 * with the claude and codex CLIs. Identical convergence and failure policy across
 * `.sh` and `.ps1`: per server, an existing registration of the same name is
 * removed (best-effort — a "not found" failure is not an error) and then added,
 * so a changed url replaces the prior registration on re-run. Registration is
 * attempted with each agent whose CLI is present on PATH; an absent CLI is
 * skipped with a message; the step exits non-zero only when a present CLI's add
 * fails.
 */
export function generateMcpRegistrationScript(servers: McpServer[], ext: ScriptExtension): string {
  return ext === 'sh' ? generateShScript(servers) : generatePs1Script(servers);
}

const HEADER_LINES = [
  'Registers Host MCP servers (declared in mcp-servers.yaml) with the claude and',
  'codex CLIs. Generated by `configamatron update-shares` -- do not edit by hand.',
  "Re-running converges: any existing registration of a server's name is removed",
  '(idempotent, best-effort) before it is re-added, so a changed url replaces the',
  "prior registration. Fails non-zero only if a present CLI's add returns an error.",
];

function generateShScript(servers: McpServer[]): string {
  const lines: string[] = [
    '#!/usr/bin/env bash',
    'set -uo pipefail',
    '',
    ...HEADER_LINES.map((l) => `# ${l}`),
    '',
    'status=0',
    '',
    'if command -v claude >/dev/null 2>&1; then',
  ];
  for (const s of servers) {
    lines.push(
      `    claude mcp remove ${shQuote(s.name)} >/dev/null 2>&1`,
      `    if ! claude mcp add --transport http ${shQuote(s.name)} ${shQuote(s.url)}; then`,
      `        echo "register-mcp-servers: claude mcp add failed for '${s.name}'" >&2`,
      '        status=1',
      '    fi',
    );
  }
  lines.push(
    'else',
    '    echo "register-mcp-servers: claude CLI not found on PATH; skipping claude registration"',
    'fi',
    '',
    'if command -v codex >/dev/null 2>&1; then',
  );
  for (const s of servers) {
    lines.push(
      `    codex mcp remove ${shQuote(s.name)} >/dev/null 2>&1`,
      `    if ! codex mcp add ${shQuote(s.name)} --url ${shQuote(s.url)}; then`,
      `        echo "register-mcp-servers: codex mcp add failed for '${s.name}'" >&2`,
      '        status=1',
      '    fi',
    );
  }
  lines.push(
    'else',
    '    echo "register-mcp-servers: codex CLI not found on PATH; skipping codex registration"',
    'fi',
    '',
    'exit "$status"',
    '',
  );
  return lines.join('\n');
}

function generatePs1Script(servers: McpServer[]): string {
  const lines: string[] = [
    ...HEADER_LINES.map((l) => `# ${l}`),
    '',
    '$exitCode = 0',
    '',
    'if (Get-Command claude -ErrorAction SilentlyContinue) {',
  ];
  for (const s of servers) {
    lines.push(
      `    claude mcp remove ${psQuote(s.name)} *> $null`,
      `    claude mcp add --transport http ${psQuote(s.name)} ${psQuote(s.url)}`,
      '    if ($LASTEXITCODE -ne 0) {',
      `        Write-Error "register-mcp-servers: claude mcp add failed for '${s.name}'"`,
      '        $exitCode = 1',
      '    }',
    );
  }
  lines.push(
    '} else {',
    '    Write-Host "register-mcp-servers: claude CLI not found on PATH; skipping claude registration"',
    '}',
    '',
    'if (Get-Command codex -ErrorAction SilentlyContinue) {',
  );
  for (const s of servers) {
    lines.push(
      `    codex mcp remove ${psQuote(s.name)} *> $null`,
      `    codex mcp add ${psQuote(s.name)} --url ${psQuote(s.url)}`,
      '    if ($LASTEXITCODE -ne 0) {',
      `        Write-Error "register-mcp-servers: codex mcp add failed for '${s.name}'"`,
      '        $exitCode = 1',
      '    }',
    );
  }
  lines.push(
    '} else {',
    '    Write-Host "register-mcp-servers: codex CLI not found on PATH; skipping codex registration"',
    '}',
    '',
    'exit $exitCode',
    '',
  );
  return lines.join('\n');
}

function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function psQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}
